organstops = {
"Aeoline": [['Aéoline', 'Éolienne'] , "String", "an extremely small scaled stop with a very delicate, airy tone; built frequently as a single-rank stop, or as a double-rank celeste."],
"Baryton": [[] , "Reed", "16' or 8' reed stop imitative of the instrument"],
"Blockflöte": [[] , "Flute", "German for \"recorder\"; a wide scaled conical or stopped flute of 4′ or 2′ pitch, taking its name from the common flute called a \"recorder\" which its tone closely resembles"],
"Bombarde": [[] , "Reed", "a powerful chorus reed stop with a brassy timbre, occurring on the manuals at 16′ (and occasionally 8′), or in the pedal at 16′ or 32′ pitch; similar tone as the Ophicleide or Trombone"],
"Bourdon": [[] , "Flute", "a wide-scaled stopped-flute, 16′ or 8′ on the manuals, and 16′ or 32′ in the pedals (where it may be called Subbass or Contra Bourdon)"],
"Cello": [['Violoncelle'] , "String", "a string stop at 8′ or 16′; has a warmer, more \"romantic\" tone than the Gamba"],
"Chimney Flute": [[] , "Flute", "a stopped flue stop with a chimneyed stopper."],
"Choralbass": [[] , "Principal", "a 4′ strongly voiced octave Diapason in the pedal division, mainly for cantus firmus use"],
"Claribel": [['Clarabel', 'Flute', 'Claribel', 'Flute', 'Melodia'] , "Flute", "an 8′ open wood manual stop."],
"Clarinet": [['Clarinette', 'Clarionet'] , "Reed", "a reed stop with a rich tone imitating the orchestral instrument"],
"Clarion": [['Clairon'] , "Reed", "4′ or 2′ Trumpet, it is a chorus reed"],
"Cor Anglais": [[] , "Reed", "16' or 8' reed stop imitative of the instrument."],
"Cornet": [[] , "Flute", "A multi-rank stop consisting of up to five ranks of wide-scaled pipes.  The pitches include 8′, 4′, ​2 2⁄3′, 2′ and ​1 3⁄5′. Three- and four-rank cornets eliminate 8′ and 4′ ranks. This stop is not imitative of the orchestral cornet."],
"Cornopean": [[] , "Reed", "8′ chorus reed similar to the Trumpet; normally located in the Swell division."],
"Cromorne": [['KrummhornCremona'] , "Reed", "Cylindrical solo reed that has a distinct buzzing or bleating sound, imitative of the historical instrument of the same name"],
"Diapason": [['Montre', 'Open', 'Diapason', 'Principale', 'Principal', 'Prinzipal', 'Tenori[1]'] , "Principal", "A flue stop that is the \"backbone\" sound of the organ. Most commonly at 8′ in manuals, and 8′ or 16′ in the pedals."],
"Diaphone": [[] , "", "A special type of organ pipe that produces tone by using a felt hammer to beat air through the resonator. Common on theatre organs, not often used in classical instruments."],
"Dulcian": [[] , "Reed", "A reed stop at 8' pitch on the manuals with a tone similar to that of a bassoon."],
"Dulciana": [[] , "String", "An 8' metal string stop. Usually the softest stop on an organ."],
"Fagotto": [['Bassoon', 'Fagot'] , "Reed", "16' chorus reed. Inverted conical construction, softer than a trumpet or trombone."],
"Flageolet": [[] , "Flute", "A flute stop of 2' or 1' pitch."],
"Fugara": [[] , "Principal/String hybrid", "A flue stop in 4' or 8' pitch. The tone has a sharp \"stringy\" quality.[2]"],
"Gamba": [['Viola', 'da', 'Gamba', 'Viole'] , "String", "A string stop that has a thinner, more cutting tone than the Cello stop. It one of the earliest designs of string stops, and is named after the Baroque instrument viola da gamba."],
"Gedackt": [['Gedeckt', 'Stopped', 'Diapason'] , "Flute", "A basic stopped 8′ flute in the manuals, and stopped 16′ and/or 8′ flute voice in the pedal"],
"Gemshorn": [['Cor', 'de', 'Chamois'] , "Flute/String hybrid", "A flue stop usually at 4', 2', pitch but sometimes 8' pitch; similar tone as Spitz Flute"],
"Gravissima": [[] , "", "Name for a resultant 64' flue (a 32' stop combined with a 21​2⁄3' stop, which is a fifth, producing a difference tone of 8 Hz on low C.)"],
"Harmonic Flute": [[] , "Flute", "An open metal flute made to sound an octave above its length by means of a small hole at its midpoint. This stop has a very pure flute tone and was popularized by Aristide Cavaillé-Coll."],
"Hohlflöte": [['Hohlflute', 'Holpijp'] , "Flute", "A metal or wooden 8' open or stopped flute."],
"Keraulophon": [[] , "Flute", "A flue stop at 8' pitch with a stringy, reedy tone."],
"Larigot": [[] , "Flute", "Flute mutation stop at ​1 1⁄3′ pitch"],
"Mixture": [['Fourniture', 'Plein', 'Jeu'] , "Principal", "Multi-rank stops that enhance the harmonics of the fundamental pitch, and are intended for use with foundation stops, not alone. Mixture IV indicates that the stop has four ranks. Mixture 15.19.22.26 indicates the composition."],
"Nachthorn": [['Night', 'Horn', 'Cor', 'de', 'Nuit', 'Corno', 'de', 'Nacht'] , "Flute", "wide-scaled flute with a relatively small mouth, produces a soft, but penetrating sound; occurring at 8′ and 4′ pitch, and also at 2′ pitch at pedal"],
"Nasard": [['Nasat', 'Nazard'] , "Flute", "Flute mutation stop of ​2 2⁄3′ (sounding a twelfth above written pitch)"],
"Nason Flute": [[] , "Flute", "Flute stop with stopped pipes. Usually 4′ pitch in which the twelfth is often prominent"],
"None": [[] , "Flute", "A rare mutation stop of 8/9', reinforcing the 8' harmonic series. (sounds a twentieth above written pitch)"],
"Oboe": [['Hautbois'] , "Reed", "8' reed stop used as both a solo stop and a chorus reed."],
"Octave": [['Oktav', 'Prestant', 'Principal'] , "Principal", "A 4′ Principal. \"Prestant\" often indicates ranks that have pipes mounted in the front of the organ case.[3]"],
"Octavin": [[] , "Principal", "1' principal"],
"Ophicleide": [[] , "Reed", "powerful reed stop, much like the Bombarde or Trombone; normally a 16′ or 32′ pedal reed; unusually an 8′ or 16′ on the manuals"],
"Orchestral Oboe": [[] , "Reed", "a different stop from Oboe; intended to imitate the orchestral instrument; of smaller scale than the non-imitative oboe"],
"Piccolo": [[] , "Flute", "2′ or 1' flute"],
"Quarte": [[] , "Flute", "2′ flute on 17th and 18th century French organs; short for Quarte de nasard, sounding an interval of a fourth above the nasard stop"],
"Quint": [[] , "Flute", "a resultant mutation stop, 5 1/3' on the manuals reinforcing the 16' harmonic series or 10 2/3' in the pedal reinforcing the 32' harmonic series.."],
"Quintadena": [['Quintaton'] , "Flute", "Flue stop of 4′, 8′, or 16′ foot pitch with stopped pipes and a flute tone in which the twelfth is prominent"],
"Regal": [[] , "Reed", "a reed stop with fractional-length resonators; produces a buzzy sound with low fundamental frequency."],
"Rohrflöte": [['Chimney', 'Flute'] , "Flute", "German for \"reed flute\"; a semi-capped metal pipe with a narrow, open-ended tube (i.e. \"chimney\") extending from the top which resembles a reed"],
"Salicional": [[] , "Principal/String hybrid", "An 8′ string stop, softer in tone than the Gamba"],
"Scharf": [['Cymbale'] , "Principal", "A high-pitched mixture stop"],
"Sesquialtera": [[] , "Flute", "Comprises ranks at 2​2⁄3' and 1​3⁄5. The 2' rank will be added on a III rank sesquilatera"],
"Sifflöte": [['Sifflet'] , "Flute", "1′ flute"],
"Spitz Flute": [[] , "Flute/String hybrid", "4' or 2' flute with metal pipes tapered to a point at the top; similar tone as Gemshorn"],
"Suabe Flute": [[] , "Flute", "Flute stop of 4′ pitch or 8′ pitch with a bright, clear tone."],
"Super Octave": [['Doublette', 'Fifteenth'] , "Principal", "the manual 2′ Principal or Diapason; its name merely signifies that it is above (i.e. \"super\") the 4′ Octave."],
"Tibia Clausa": [['Tibia'] , "Flute", "a large-scale, stopped wood flute pipe, usually with a leathered lip; performs same function in a theatre pipe organ as a principal in a classical organ."],
"Tierce": [['Seventeenth', 'Terz', 'Tertia'] , "Flute", "mutation stop pitched ​1 3⁄5′, supporting the 8′ harmonic series"],
"Trichterregal": [[] , "Reed", "an 8-ft reed stop on a pipe organ with funnel-shaped resonators.[4][5] A trichterregal was used by Schnitger in the Schnitger organ that he built for St. James's Church, Hamburg."],
"Trombone": [['Posaune'] , "Reed", "Chorus reed simulating the trombone; most commonly in the pedal at 16′ or 32′ pitch; similar tone as Bombarde or Ophicleide"],
"Trompette en Chamade": [[] , "Reed", "Solo trumpet laid horizontally; can often be heard over full organ."],
"Trompette Militaire": [[] , "Reed", "powerful solo reed of the trumpet-family, with a brassy, penetrating tone"],
"Trumpet": [['Trompete', 'Trompette'] , "Reed", "a loud chorus reed stop, generally a single rank, with inverted conical resonators."],
"Tuba": [[] , "Reed", "large-scale, high pressure, smooth solo reed usually 8′ in the manuals and 16′ (sometimes 32′) in the pedal. Tuba is Latin for Trumpet; it is not named after the orchestral tuba."],
"Twelfth": [[] , "Principal", "principal mutation stop of ​2 2⁄3′"],
"Twenty-Second": [['Kleine', 'Principal'] , "Principal", "a 1′ principal"],
"Unda Maris": [[] , "Flute", "Latin for \"wave of the sea\"; a very soft rank tuned slightly sharp or flat. It is drawn with another soft rank to create an undulating effect. Occasionally built as a double-rank stop called Unda Maris II, which has both a normal-pitched and detuned rank."],
"Voix Céleste": [[] , "String", "An 8′ string stop tuned slightly sharp or flat to create an undulating effect when combined with another string stop. Some variants contain both a normal-pitched and detuned rank."],
"Vox Angelica": [[] , "String", "A soft organ flue stop tuned slightly flat."],
"Vox Humana": [['Voix', 'humaine'] , "Reed", "fractional length regal supposedly intended to imitate the human voice"]
}